apiVersion: apps/v1
kind: Deployment
metadata:
  name: abdelalim-deploy   
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
       name: test
    spec:
      containers:
      - name: sise
        image: shamndor/firstdocker
        ports:
        - containerPort: 9876
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "1.0"