apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydocker
  name: mydocker  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydocker     
  template:
    metadata:
      labels:
       name: mydocker
    spec:
      containers:
      - name: sise
        image: shamndor/firstdocker
        ports:
        - containerPort: 9876
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "1.0"